#!/bin/sh
. "$(dirname $0)/_/husky.sh"

echo "[pre-commit] Start pre-commit check"

npm run lint
# Eslint check all files
if [[ "$?" == 1 ]]; then
    echo "ESlint check fail, abort git push"
    exit 1
fi
echo "Pass for Eslint check"
echo "[pre-commit] successfully"

